//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Customer
{
	public virtual string Name
	{
		get;
		set;
	}

	public virtual string Address
	{
		get;
		set;
	}

	public virtual Payment Payment
	{
		get;
		set;
	}

	public virtual string GetName(int Id)
	{
		throw new System.NotImplementedException();
	}

}

